// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"sync"

	"github.com/yousysadmin/igit/internal/git"
)

// DiffSourceMock is a mock implementation of git.Renderer.
//
//	func TestSomethingThatUsesRenderer(t *testing.T) {
//
//		// make and configure a mocked git.Renderer
//		mockedRenderer := &DiffSourceMock{
//			ChangedFilesFunc: func(ref string, staged bool) ([]git.FileEntry, error) {
//				panic("mock out the ChangedFiles method")
//			},
//			FileDiffFunc: func(req git.FileDiffRequest) ([]git.DiffLine, error) {
//				panic("mock out the FileDiff method")
//			},
//		}
//
//		// use mockedRenderer in code that requires git.Renderer
//		// and then make assertions.
//
//	}
type DiffSourceMock struct {
	// ChangedFilesFunc mocks the ChangedFiles method.
	ChangedFilesFunc func(ref string, staged bool) ([]git.FileEntry, error)

	// FileDiffFunc mocks the FileDiff method.
	FileDiffFunc func(req git.FileDiffRequest) ([]git.DiffLine, error)

	// calls tracks calls to the methods.
	calls struct {
		// ChangedFiles holds details about calls to the ChangedFiles method.
		ChangedFiles []struct {
			// Ref is the ref argument value.
			Ref string
			// Staged is the staged argument value.
			Staged bool
		}
		// FileDiff holds details about calls to the FileDiff method.
		FileDiff []struct {
			// Req is the req argument value.
			Req git.FileDiffRequest
		}
	}
	lockChangedFiles sync.RWMutex
	lockFileDiff     sync.RWMutex
}

// ChangedFiles calls ChangedFilesFunc.
func (mock *DiffSourceMock) ChangedFiles(ref string, staged bool) ([]git.FileEntry, error) {
	if mock.ChangedFilesFunc == nil {
		panic("DiffSourceMock.ChangedFilesFunc: method is nil but Renderer.ChangedFiles was just called")
	}
	callInfo := struct {
		Ref    string
		Staged bool
	}{
		Ref:    ref,
		Staged: staged,
	}
	mock.lockChangedFiles.Lock()
	mock.calls.ChangedFiles = append(mock.calls.ChangedFiles, callInfo)
	mock.lockChangedFiles.Unlock()
	return mock.ChangedFilesFunc(ref, staged)
}

// ChangedFilesCalls gets all the calls that were made to ChangedFiles.
// Check the length with:
//
//	len(mockedRenderer.ChangedFilesCalls())
func (mock *DiffSourceMock) ChangedFilesCalls() []struct {
	Ref    string
	Staged bool
} {
	var calls []struct {
		Ref    string
		Staged bool
	}
	mock.lockChangedFiles.RLock()
	calls = mock.calls.ChangedFiles
	mock.lockChangedFiles.RUnlock()
	return calls
}

// FileDiff calls FileDiffFunc.
func (mock *DiffSourceMock) FileDiff(req git.FileDiffRequest) ([]git.DiffLine, error) {
	if mock.FileDiffFunc == nil {
		panic("DiffSourceMock.FileDiffFunc: method is nil but Renderer.FileDiff was just called")
	}
	callInfo := struct {
		Req git.FileDiffRequest
	}{
		Req: req,
	}
	mock.lockFileDiff.Lock()
	mock.calls.FileDiff = append(mock.calls.FileDiff, callInfo)
	mock.lockFileDiff.Unlock()
	return mock.FileDiffFunc(req)
}

// FileDiffCalls gets all the calls that were made to FileDiff.
// Check the length with:
//
//	len(mockedRenderer.FileDiffCalls())
func (mock *DiffSourceMock) FileDiffCalls() []struct {
	Req git.FileDiffRequest
} {
	var calls []struct {
		Req git.FileDiffRequest
	}
	mock.lockFileDiff.RLock()
	calls = mock.calls.FileDiff
	mock.lockFileDiff.RUnlock()
	return calls
}
