// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"os/exec"
	"sync"

	"github.com/yousysadmin/igit/internal/conflict"
	"github.com/yousysadmin/igit/internal/git"
	"github.com/yousysadmin/igit/internal/gitops"
)

// RepoMock is a mock implementation of tui.Repo.
//
//	func TestSomethingThatUsesRepo(t *testing.T) {
//
//		// make and configure a mocked tui.Repo
//		mockedRepo := &RepoMock{
//			AbortOperationFunc: func(ctx context.Context, state gitops.RepoState) error {
//				panic("mock out the AbortOperation method")
//			},
//			ApplyLinesFunc: func(ctx context.Context, req gitops.LineRequest) error {
//				panic("mock out the ApplyLines method")
//			},
//			BranchesFunc: func(ctx context.Context) ([]gitops.Branch, error) {
//				panic("mock out the Branches method")
//			},
//			CheckoutFunc: func(ctx context.Context, name string, force bool) error {
//				panic("mock out the Checkout method")
//			},
//			CheckoutRemoteFunc: func(ctx context.Context, remoteRef string, force bool) error {
//				panic("mock out the CheckoutRemote method")
//			},
//			CommitFunc: func(ctx context.Context, msg string, o gitops.CommitOpts) error {
//				panic("mock out the Commit method")
//			},
//			CommitEditorCmdFunc: func(o gitops.CommitOpts, seed string) (*exec.Cmd, func(), error) {
//				panic("mock out the CommitEditorCmd method")
//			},
//			CommitFileCmdFunc: func(o gitops.CommitOpts, msg string) (*exec.Cmd, func(), error) {
//				panic("mock out the CommitFileCmd method")
//			},
//			CommitFilesFunc: func(ctx context.Context, hash string) ([]git.FileEntry, error) {
//				panic("mock out the CommitFiles method")
//			},
//			CommitMessagesFunc: func(ctx context.Context, n int) ([]string, error) {
//				panic("mock out the CommitMessages method")
//			},
//			ConflictRegionsFunc: func(path string) ([]conflict.Region, error) {
//				panic("mock out the ConflictRegions method")
//			},
//			ContinueCmdFunc: func(state gitops.RepoState) (*exec.Cmd, error) {
//				panic("mock out the ContinueCmd method")
//			},
//			CreateBranchFunc: func(ctx context.Context, name string, base string, checkout bool) error {
//				panic("mock out the CreateBranch method")
//			},
//			DeleteBranchFunc: func(ctx context.Context, name string, force bool) error {
//				panic("mock out the DeleteBranch method")
//			},
//			DiscardFunc: func(ctx context.Context, f gitops.StatusEntry, scope gitops.DiscardScope, unborn bool) error {
//				panic("mock out the Discard method")
//			},
//			FetchCmdFunc: func(all bool, prune bool) *exec.Cmd {
//				panic("mock out the FetchCmd method")
//			},
//			GPGSignEnabledFunc: func(ctx context.Context) bool {
//				panic("mock out the GPGSignEnabled method")
//			},
//			HasStagedChangesFunc: func(ctx context.Context) (bool, error) {
//				panic("mock out the HasStagedChanges method")
//			},
//			LastCommitMessageFunc: func(ctx context.Context) (string, error) {
//				panic("mock out the LastCommitMessage method")
//			},
//			LogFunc: func(ctx context.Context, ref string, limit int) ([]gitops.Commit, error) {
//				panic("mock out the Log method")
//			},
//			MergeFunc: func(ctx context.Context, name string, o gitops.MergeOpts) error {
//				panic("mock out the Merge method")
//			},
//			PullCmdFunc: func(o gitops.PullOpts) *exec.Cmd {
//				panic("mock out the PullCmd method")
//			},
//			PushCmdFunc: func(o gitops.PushOpts) *exec.Cmd {
//				panic("mock out the PushCmd method")
//			},
//			RangeDiffFunc: func(ctx context.Context, ref string, contextLines int) (string, error) {
//				panic("mock out the RangeDiff method")
//			},
//			RebaseFunc: func(ctx context.Context, onto string, o gitops.RebaseOpts) error {
//				panic("mock out the Rebase method")
//			},
//			RemotesFunc: func(ctx context.Context) ([]string, error) {
//				panic("mock out the Remotes method")
//			},
//			RenameBranchFunc: func(ctx context.Context, oldName string, newName string) error {
//				panic("mock out the RenameBranch method")
//			},
//			ResetFunc: func(ctx context.Context, ref string, mode gitops.ResetMode) error {
//				panic("mock out the Reset method")
//			},
//			ResolveConflictFunc: func(ctx context.Context, path string, ours bool) error {
//				panic("mock out the ResolveConflict method")
//			},
//			ResolveConflictRegionFunc: func(path string, index int, choice conflict.Choice) error {
//				panic("mock out the ResolveConflictRegion method")
//			},
//			SetUpstreamFunc: func(ctx context.Context, branch string, remote string, remoteBranch string) error {
//				panic("mock out the SetUpstream method")
//			},
//			StageAllFunc: func(ctx context.Context) error {
//				panic("mock out the StageAll method")
//			},
//			StageFilesFunc: func(ctx context.Context, paths []string) error {
//				panic("mock out the StageFiles method")
//			},
//			StagingDiffFunc: func(ctx context.Context, spec gitops.DiffSpec) (string, error) {
//				panic("mock out the StagingDiff method")
//			},
//			StashApplyFunc: func(ctx context.Context, index int) error {
//				panic("mock out the StashApply method")
//			},
//			StashDropFunc: func(ctx context.Context, index int) error {
//				panic("mock out the StashDrop method")
//			},
//			StashFilesFunc: func(ctx context.Context, index int) ([]git.FileEntry, error) {
//				panic("mock out the StashFiles method")
//			},
//			StashPopFunc: func(ctx context.Context, index int) error {
//				panic("mock out the StashPop method")
//			},
//			StashPushFunc: func(ctx context.Context, o gitops.StashPushOpts) error {
//				panic("mock out the StashPush method")
//			},
//			StashStagedSupportedFunc: func(ctx context.Context) bool {
//				panic("mock out the StashStagedSupported method")
//			},
//			StashesFunc: func(ctx context.Context) ([]gitops.StashEntry, error) {
//				panic("mock out the Stashes method")
//			},
//			StatusFunc: func(ctx context.Context) (gitops.Status, error) {
//				panic("mock out the Status method")
//			},
//			UnstageAllFunc: func(ctx context.Context, unborn bool) error {
//				panic("mock out the UnstageAll method")
//			},
//			UnstageDuringMergeFunc: func(ctx context.Context, path string, unborn bool) error {
//				panic("mock out the UnstageDuringMerge method")
//			},
//			UnstageFilesFunc: func(ctx context.Context, paths []string, unborn bool) error {
//				panic("mock out the UnstageFiles method")
//			},
//		}
//
//		// use mockedRepo in code that requires tui.Repo
//		// and then make assertions.
//
//	}
type RepoMock struct {
	// AbortOperationFunc mocks the AbortOperation method.
	AbortOperationFunc func(ctx context.Context, state gitops.RepoState) error

	// ApplyLinesFunc mocks the ApplyLines method.
	ApplyLinesFunc func(ctx context.Context, req gitops.LineRequest) error

	// BranchesFunc mocks the Branches method.
	BranchesFunc func(ctx context.Context) ([]gitops.Branch, error)

	// CheckoutFunc mocks the Checkout method.
	CheckoutFunc func(ctx context.Context, name string, force bool) error

	// CheckoutRemoteFunc mocks the CheckoutRemote method.
	CheckoutRemoteFunc func(ctx context.Context, remoteRef string, force bool) error

	// CommitFunc mocks the Commit method.
	CommitFunc func(ctx context.Context, msg string, o gitops.CommitOpts) error

	// CommitEditorCmdFunc mocks the CommitEditorCmd method.
	CommitEditorCmdFunc func(o gitops.CommitOpts, seed string) (*exec.Cmd, func(), error)

	// CommitFileCmdFunc mocks the CommitFileCmd method.
	CommitFileCmdFunc func(o gitops.CommitOpts, msg string) (*exec.Cmd, func(), error)

	// CommitFilesFunc mocks the CommitFiles method.
	CommitFilesFunc func(ctx context.Context, hash string) ([]git.FileEntry, error)

	// CommitMessagesFunc mocks the CommitMessages method.
	CommitMessagesFunc func(ctx context.Context, n int) ([]string, error)

	// ConflictRegionsFunc mocks the ConflictRegions method.
	ConflictRegionsFunc func(path string) ([]conflict.Region, error)

	// ContinueCmdFunc mocks the ContinueCmd method.
	ContinueCmdFunc func(state gitops.RepoState) (*exec.Cmd, error)

	// CreateBranchFunc mocks the CreateBranch method.
	CreateBranchFunc func(ctx context.Context, name string, base string, checkout bool) error

	// DeleteBranchFunc mocks the DeleteBranch method.
	DeleteBranchFunc func(ctx context.Context, name string, force bool) error

	// DiscardFunc mocks the Discard method.
	DiscardFunc func(ctx context.Context, f gitops.StatusEntry, scope gitops.DiscardScope, unborn bool) error

	// FetchCmdFunc mocks the FetchCmd method.
	FetchCmdFunc func(all bool, prune bool) *exec.Cmd

	// GPGSignEnabledFunc mocks the GPGSignEnabled method.
	GPGSignEnabledFunc func(ctx context.Context) bool

	// HasStagedChangesFunc mocks the HasStagedChanges method.
	HasStagedChangesFunc func(ctx context.Context) (bool, error)

	// LastCommitMessageFunc mocks the LastCommitMessage method.
	LastCommitMessageFunc func(ctx context.Context) (string, error)

	// LogFunc mocks the Log method.
	LogFunc func(ctx context.Context, ref string, limit int) ([]gitops.Commit, error)

	// MergeFunc mocks the Merge method.
	MergeFunc func(ctx context.Context, name string, o gitops.MergeOpts) error

	// PullCmdFunc mocks the PullCmd method.
	PullCmdFunc func(o gitops.PullOpts) *exec.Cmd

	// PushCmdFunc mocks the PushCmd method.
	PushCmdFunc func(o gitops.PushOpts) *exec.Cmd

	// RangeDiffFunc mocks the RangeDiff method.
	RangeDiffFunc func(ctx context.Context, ref string, contextLines int) (string, error)

	// RebaseFunc mocks the Rebase method.
	RebaseFunc func(ctx context.Context, onto string, o gitops.RebaseOpts) error

	// RemotesFunc mocks the Remotes method.
	RemotesFunc func(ctx context.Context) ([]string, error)

	// RenameBranchFunc mocks the RenameBranch method.
	RenameBranchFunc func(ctx context.Context, oldName string, newName string) error

	// ResetFunc mocks the Reset method.
	ResetFunc func(ctx context.Context, ref string, mode gitops.ResetMode) error

	// ResolveConflictFunc mocks the ResolveConflict method.
	ResolveConflictFunc func(ctx context.Context, path string, ours bool) error

	// ResolveConflictRegionFunc mocks the ResolveConflictRegion method.
	ResolveConflictRegionFunc func(path string, index int, choice conflict.Choice) error

	// SetUpstreamFunc mocks the SetUpstream method.
	SetUpstreamFunc func(ctx context.Context, branch string, remote string, remoteBranch string) error

	// StageAllFunc mocks the StageAll method.
	StageAllFunc func(ctx context.Context) error

	// StageFilesFunc mocks the StageFiles method.
	StageFilesFunc func(ctx context.Context, paths []string) error

	// StagingDiffFunc mocks the StagingDiff method.
	StagingDiffFunc func(ctx context.Context, spec gitops.DiffSpec) (string, error)

	// StashApplyFunc mocks the StashApply method.
	StashApplyFunc func(ctx context.Context, index int) error

	// StashDropFunc mocks the StashDrop method.
	StashDropFunc func(ctx context.Context, index int) error

	// StashFilesFunc mocks the StashFiles method.
	StashFilesFunc func(ctx context.Context, index int) ([]git.FileEntry, error)

	// StashPopFunc mocks the StashPop method.
	StashPopFunc func(ctx context.Context, index int) error

	// StashPushFunc mocks the StashPush method.
	StashPushFunc func(ctx context.Context, o gitops.StashPushOpts) error

	// StashStagedSupportedFunc mocks the StashStagedSupported method.
	StashStagedSupportedFunc func(ctx context.Context) bool

	// StashesFunc mocks the Stashes method.
	StashesFunc func(ctx context.Context) ([]gitops.StashEntry, error)

	// StatusFunc mocks the Status method.
	StatusFunc func(ctx context.Context) (gitops.Status, error)

	// UnstageAllFunc mocks the UnstageAll method.
	UnstageAllFunc func(ctx context.Context, unborn bool) error

	// UnstageDuringMergeFunc mocks the UnstageDuringMerge method.
	UnstageDuringMergeFunc func(ctx context.Context, path string, unborn bool) error

	// UnstageFilesFunc mocks the UnstageFiles method.
	UnstageFilesFunc func(ctx context.Context, paths []string, unborn bool) error

	// calls tracks calls to the methods.
	calls struct {
		// AbortOperation holds details about calls to the AbortOperation method.
		AbortOperation []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// State is the state argument value.
			State gitops.RepoState
		}
		// ApplyLines holds details about calls to the ApplyLines method.
		ApplyLines []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req gitops.LineRequest
		}
		// Branches holds details about calls to the Branches method.
		Branches []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// Checkout holds details about calls to the Checkout method.
		Checkout []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
			// Force is the force argument value.
			Force bool
		}
		// CheckoutRemote holds details about calls to the CheckoutRemote method.
		CheckoutRemote []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// RemoteRef is the remoteRef argument value.
			RemoteRef string
			// Force is the force argument value.
			Force bool
		}
		// Commit holds details about calls to the Commit method.
		Commit []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Msg is the msg argument value.
			Msg string
			// O is the o argument value.
			O gitops.CommitOpts
		}
		// CommitEditorCmd holds details about calls to the CommitEditorCmd method.
		CommitEditorCmd []struct {
			// O is the o argument value.
			O gitops.CommitOpts
			// Seed is the seed argument value.
			Seed string
		}
		// CommitFileCmd holds details about calls to the CommitFileCmd method.
		CommitFileCmd []struct {
			// O is the o argument value.
			O gitops.CommitOpts
			// Msg is the msg argument value.
			Msg string
		}
		// CommitFiles holds details about calls to the CommitFiles method.
		CommitFiles []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Hash is the hash argument value.
			Hash string
		}
		// CommitMessages holds details about calls to the CommitMessages method.
		CommitMessages []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// N is the n argument value.
			N int
		}
		// ConflictRegions holds details about calls to the ConflictRegions method.
		ConflictRegions []struct {
			// Path is the path argument value.
			Path string
		}
		// ContinueCmd holds details about calls to the ContinueCmd method.
		ContinueCmd []struct {
			// State is the state argument value.
			State gitops.RepoState
		}
		// CreateBranch holds details about calls to the CreateBranch method.
		CreateBranch []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
			// Base is the base argument value.
			Base string
			// Checkout is the checkout argument value.
			Checkout bool
		}
		// DeleteBranch holds details about calls to the DeleteBranch method.
		DeleteBranch []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
			// Force is the force argument value.
			Force bool
		}
		// Discard holds details about calls to the Discard method.
		Discard []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// F is the f argument value.
			F gitops.StatusEntry
			// Scope is the scope argument value.
			Scope gitops.DiscardScope
			// Unborn is the unborn argument value.
			Unborn bool
		}
		// FetchCmd holds details about calls to the FetchCmd method.
		FetchCmd []struct {
			// All is the all argument value.
			All bool
			// Prune is the prune argument value.
			Prune bool
		}
		// GPGSignEnabled holds details about calls to the GPGSignEnabled method.
		GPGSignEnabled []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// HasStagedChanges holds details about calls to the HasStagedChanges method.
		HasStagedChanges []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// LastCommitMessage holds details about calls to the LastCommitMessage method.
		LastCommitMessage []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// Log holds details about calls to the Log method.
		Log []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Ref is the ref argument value.
			Ref string
			// Limit is the limit argument value.
			Limit int
		}
		// Merge holds details about calls to the Merge method.
		Merge []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
			// O is the o argument value.
			O gitops.MergeOpts
		}
		// PullCmd holds details about calls to the PullCmd method.
		PullCmd []struct {
			// O is the o argument value.
			O gitops.PullOpts
		}
		// PushCmd holds details about calls to the PushCmd method.
		PushCmd []struct {
			// O is the o argument value.
			O gitops.PushOpts
		}
		// RangeDiff holds details about calls to the RangeDiff method.
		RangeDiff []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Ref is the ref argument value.
			Ref string
			// ContextLines is the contextLines argument value.
			ContextLines int
		}
		// Rebase holds details about calls to the Rebase method.
		Rebase []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Onto is the onto argument value.
			Onto string
			// O is the o argument value.
			O gitops.RebaseOpts
		}
		// Remotes holds details about calls to the Remotes method.
		Remotes []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// RenameBranch holds details about calls to the RenameBranch method.
		RenameBranch []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OldName is the oldName argument value.
			OldName string
			// NewName is the newName argument value.
			NewName string
		}
		// Reset holds details about calls to the Reset method.
		Reset []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Ref is the ref argument value.
			Ref string
			// Mode is the mode argument value.
			Mode gitops.ResetMode
		}
		// ResolveConflict holds details about calls to the ResolveConflict method.
		ResolveConflict []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Path is the path argument value.
			Path string
			// Ours is the ours argument value.
			Ours bool
		}
		// ResolveConflictRegion holds details about calls to the ResolveConflictRegion method.
		ResolveConflictRegion []struct {
			// Path is the path argument value.
			Path string
			// Index is the index argument value.
			Index int
			// Choice is the choice argument value.
			Choice conflict.Choice
		}
		// SetUpstream holds details about calls to the SetUpstream method.
		SetUpstream []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Branch is the branch argument value.
			Branch string
			// Remote is the remote argument value.
			Remote string
			// RemoteBranch is the remoteBranch argument value.
			RemoteBranch string
		}
		// StageAll holds details about calls to the StageAll method.
		StageAll []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// StageFiles holds details about calls to the StageFiles method.
		StageFiles []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Paths is the paths argument value.
			Paths []string
		}
		// StagingDiff holds details about calls to the StagingDiff method.
		StagingDiff []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Spec is the spec argument value.
			Spec gitops.DiffSpec
		}
		// StashApply holds details about calls to the StashApply method.
		StashApply []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Index is the index argument value.
			Index int
		}
		// StashDrop holds details about calls to the StashDrop method.
		StashDrop []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Index is the index argument value.
			Index int
		}
		// StashFiles holds details about calls to the StashFiles method.
		StashFiles []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Index is the index argument value.
			Index int
		}
		// StashPop holds details about calls to the StashPop method.
		StashPop []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Index is the index argument value.
			Index int
		}
		// StashPush holds details about calls to the StashPush method.
		StashPush []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// O is the o argument value.
			O gitops.StashPushOpts
		}
		// StashStagedSupported holds details about calls to the StashStagedSupported method.
		StashStagedSupported []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// Stashes holds details about calls to the Stashes method.
		Stashes []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// Status holds details about calls to the Status method.
		Status []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// UnstageAll holds details about calls to the UnstageAll method.
		UnstageAll []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Unborn is the unborn argument value.
			Unborn bool
		}
		// UnstageDuringMerge holds details about calls to the UnstageDuringMerge method.
		UnstageDuringMerge []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Path is the path argument value.
			Path string
			// Unborn is the unborn argument value.
			Unborn bool
		}
		// UnstageFiles holds details about calls to the UnstageFiles method.
		UnstageFiles []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Paths is the paths argument value.
			Paths []string
			// Unborn is the unborn argument value.
			Unborn bool
		}
	}
	lockAbortOperation        sync.RWMutex
	lockApplyLines            sync.RWMutex
	lockBranches              sync.RWMutex
	lockCheckout              sync.RWMutex
	lockCheckoutRemote        sync.RWMutex
	lockCommit                sync.RWMutex
	lockCommitEditorCmd       sync.RWMutex
	lockCommitFileCmd         sync.RWMutex
	lockCommitFiles           sync.RWMutex
	lockCommitMessages        sync.RWMutex
	lockConflictRegions       sync.RWMutex
	lockContinueCmd           sync.RWMutex
	lockCreateBranch          sync.RWMutex
	lockDeleteBranch          sync.RWMutex
	lockDiscard               sync.RWMutex
	lockFetchCmd              sync.RWMutex
	lockGPGSignEnabled        sync.RWMutex
	lockHasStagedChanges      sync.RWMutex
	lockLastCommitMessage     sync.RWMutex
	lockLog                   sync.RWMutex
	lockMerge                 sync.RWMutex
	lockPullCmd               sync.RWMutex
	lockPushCmd               sync.RWMutex
	lockRangeDiff             sync.RWMutex
	lockRebase                sync.RWMutex
	lockRemotes               sync.RWMutex
	lockRenameBranch          sync.RWMutex
	lockReset                 sync.RWMutex
	lockResolveConflict       sync.RWMutex
	lockResolveConflictRegion sync.RWMutex
	lockSetUpstream           sync.RWMutex
	lockStageAll              sync.RWMutex
	lockStageFiles            sync.RWMutex
	lockStagingDiff           sync.RWMutex
	lockStashApply            sync.RWMutex
	lockStashDrop             sync.RWMutex
	lockStashFiles            sync.RWMutex
	lockStashPop              sync.RWMutex
	lockStashPush             sync.RWMutex
	lockStashStagedSupported  sync.RWMutex
	lockStashes               sync.RWMutex
	lockStatus                sync.RWMutex
	lockUnstageAll            sync.RWMutex
	lockUnstageDuringMerge    sync.RWMutex
	lockUnstageFiles          sync.RWMutex
}

// AbortOperation calls AbortOperationFunc.
func (mock *RepoMock) AbortOperation(ctx context.Context, state gitops.RepoState) error {
	if mock.AbortOperationFunc == nil {
		panic("RepoMock.AbortOperationFunc: method is nil but Repo.AbortOperation was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		State gitops.RepoState
	}{
		Ctx:   ctx,
		State: state,
	}
	mock.lockAbortOperation.Lock()
	mock.calls.AbortOperation = append(mock.calls.AbortOperation, callInfo)
	mock.lockAbortOperation.Unlock()
	return mock.AbortOperationFunc(ctx, state)
}

// AbortOperationCalls gets all the calls that were made to AbortOperation.
// Check the length with:
//
//	len(mockedRepo.AbortOperationCalls())
func (mock *RepoMock) AbortOperationCalls() []struct {
	Ctx   context.Context
	State gitops.RepoState
} {
	var calls []struct {
		Ctx   context.Context
		State gitops.RepoState
	}
	mock.lockAbortOperation.RLock()
	calls = mock.calls.AbortOperation
	mock.lockAbortOperation.RUnlock()
	return calls
}

// ApplyLines calls ApplyLinesFunc.
func (mock *RepoMock) ApplyLines(ctx context.Context, req gitops.LineRequest) error {
	if mock.ApplyLinesFunc == nil {
		panic("RepoMock.ApplyLinesFunc: method is nil but Repo.ApplyLines was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Req gitops.LineRequest
	}{
		Ctx: ctx,
		Req: req,
	}
	mock.lockApplyLines.Lock()
	mock.calls.ApplyLines = append(mock.calls.ApplyLines, callInfo)
	mock.lockApplyLines.Unlock()
	return mock.ApplyLinesFunc(ctx, req)
}

// ApplyLinesCalls gets all the calls that were made to ApplyLines.
// Check the length with:
//
//	len(mockedRepo.ApplyLinesCalls())
func (mock *RepoMock) ApplyLinesCalls() []struct {
	Ctx context.Context
	Req gitops.LineRequest
} {
	var calls []struct {
		Ctx context.Context
		Req gitops.LineRequest
	}
	mock.lockApplyLines.RLock()
	calls = mock.calls.ApplyLines
	mock.lockApplyLines.RUnlock()
	return calls
}

// Branches calls BranchesFunc.
func (mock *RepoMock) Branches(ctx context.Context) ([]gitops.Branch, error) {
	if mock.BranchesFunc == nil {
		panic("RepoMock.BranchesFunc: method is nil but Repo.Branches was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockBranches.Lock()
	mock.calls.Branches = append(mock.calls.Branches, callInfo)
	mock.lockBranches.Unlock()
	return mock.BranchesFunc(ctx)
}

// BranchesCalls gets all the calls that were made to Branches.
// Check the length with:
//
//	len(mockedRepo.BranchesCalls())
func (mock *RepoMock) BranchesCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockBranches.RLock()
	calls = mock.calls.Branches
	mock.lockBranches.RUnlock()
	return calls
}

// Checkout calls CheckoutFunc.
func (mock *RepoMock) Checkout(ctx context.Context, name string, force bool) error {
	if mock.CheckoutFunc == nil {
		panic("RepoMock.CheckoutFunc: method is nil but Repo.Checkout was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Name  string
		Force bool
	}{
		Ctx:   ctx,
		Name:  name,
		Force: force,
	}
	mock.lockCheckout.Lock()
	mock.calls.Checkout = append(mock.calls.Checkout, callInfo)
	mock.lockCheckout.Unlock()
	return mock.CheckoutFunc(ctx, name, force)
}

// CheckoutCalls gets all the calls that were made to Checkout.
// Check the length with:
//
//	len(mockedRepo.CheckoutCalls())
func (mock *RepoMock) CheckoutCalls() []struct {
	Ctx   context.Context
	Name  string
	Force bool
} {
	var calls []struct {
		Ctx   context.Context
		Name  string
		Force bool
	}
	mock.lockCheckout.RLock()
	calls = mock.calls.Checkout
	mock.lockCheckout.RUnlock()
	return calls
}

// CheckoutRemote calls CheckoutRemoteFunc.
func (mock *RepoMock) CheckoutRemote(ctx context.Context, remoteRef string, force bool) error {
	if mock.CheckoutRemoteFunc == nil {
		panic("RepoMock.CheckoutRemoteFunc: method is nil but Repo.CheckoutRemote was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		RemoteRef string
		Force     bool
	}{
		Ctx:       ctx,
		RemoteRef: remoteRef,
		Force:     force,
	}
	mock.lockCheckoutRemote.Lock()
	mock.calls.CheckoutRemote = append(mock.calls.CheckoutRemote, callInfo)
	mock.lockCheckoutRemote.Unlock()
	return mock.CheckoutRemoteFunc(ctx, remoteRef, force)
}

// CheckoutRemoteCalls gets all the calls that were made to CheckoutRemote.
// Check the length with:
//
//	len(mockedRepo.CheckoutRemoteCalls())
func (mock *RepoMock) CheckoutRemoteCalls() []struct {
	Ctx       context.Context
	RemoteRef string
	Force     bool
} {
	var calls []struct {
		Ctx       context.Context
		RemoteRef string
		Force     bool
	}
	mock.lockCheckoutRemote.RLock()
	calls = mock.calls.CheckoutRemote
	mock.lockCheckoutRemote.RUnlock()
	return calls
}

// Commit calls CommitFunc.
func (mock *RepoMock) Commit(ctx context.Context, msg string, o gitops.CommitOpts) error {
	if mock.CommitFunc == nil {
		panic("RepoMock.CommitFunc: method is nil but Repo.Commit was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Msg string
		O   gitops.CommitOpts
	}{
		Ctx: ctx,
		Msg: msg,
		O:   o,
	}
	mock.lockCommit.Lock()
	mock.calls.Commit = append(mock.calls.Commit, callInfo)
	mock.lockCommit.Unlock()
	return mock.CommitFunc(ctx, msg, o)
}

// CommitCalls gets all the calls that were made to Commit.
// Check the length with:
//
//	len(mockedRepo.CommitCalls())
func (mock *RepoMock) CommitCalls() []struct {
	Ctx context.Context
	Msg string
	O   gitops.CommitOpts
} {
	var calls []struct {
		Ctx context.Context
		Msg string
		O   gitops.CommitOpts
	}
	mock.lockCommit.RLock()
	calls = mock.calls.Commit
	mock.lockCommit.RUnlock()
	return calls
}

// CommitEditorCmd calls CommitEditorCmdFunc.
func (mock *RepoMock) CommitEditorCmd(o gitops.CommitOpts, seed string) (*exec.Cmd, func(), error) {
	if mock.CommitEditorCmdFunc == nil {
		panic("RepoMock.CommitEditorCmdFunc: method is nil but Repo.CommitEditorCmd was just called")
	}
	callInfo := struct {
		O    gitops.CommitOpts
		Seed string
	}{
		O:    o,
		Seed: seed,
	}
	mock.lockCommitEditorCmd.Lock()
	mock.calls.CommitEditorCmd = append(mock.calls.CommitEditorCmd, callInfo)
	mock.lockCommitEditorCmd.Unlock()
	return mock.CommitEditorCmdFunc(o, seed)
}

// CommitEditorCmdCalls gets all the calls that were made to CommitEditorCmd.
// Check the length with:
//
//	len(mockedRepo.CommitEditorCmdCalls())
func (mock *RepoMock) CommitEditorCmdCalls() []struct {
	O    gitops.CommitOpts
	Seed string
} {
	var calls []struct {
		O    gitops.CommitOpts
		Seed string
	}
	mock.lockCommitEditorCmd.RLock()
	calls = mock.calls.CommitEditorCmd
	mock.lockCommitEditorCmd.RUnlock()
	return calls
}

// CommitFileCmd calls CommitFileCmdFunc.
func (mock *RepoMock) CommitFileCmd(o gitops.CommitOpts, msg string) (*exec.Cmd, func(), error) {
	if mock.CommitFileCmdFunc == nil {
		panic("RepoMock.CommitFileCmdFunc: method is nil but Repo.CommitFileCmd was just called")
	}
	callInfo := struct {
		O   gitops.CommitOpts
		Msg string
	}{
		O:   o,
		Msg: msg,
	}
	mock.lockCommitFileCmd.Lock()
	mock.calls.CommitFileCmd = append(mock.calls.CommitFileCmd, callInfo)
	mock.lockCommitFileCmd.Unlock()
	return mock.CommitFileCmdFunc(o, msg)
}

// CommitFileCmdCalls gets all the calls that were made to CommitFileCmd.
// Check the length with:
//
//	len(mockedRepo.CommitFileCmdCalls())
func (mock *RepoMock) CommitFileCmdCalls() []struct {
	O   gitops.CommitOpts
	Msg string
} {
	var calls []struct {
		O   gitops.CommitOpts
		Msg string
	}
	mock.lockCommitFileCmd.RLock()
	calls = mock.calls.CommitFileCmd
	mock.lockCommitFileCmd.RUnlock()
	return calls
}

// CommitFiles calls CommitFilesFunc.
func (mock *RepoMock) CommitFiles(ctx context.Context, hash string) ([]git.FileEntry, error) {
	if mock.CommitFilesFunc == nil {
		panic("RepoMock.CommitFilesFunc: method is nil but Repo.CommitFiles was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Hash string
	}{
		Ctx:  ctx,
		Hash: hash,
	}
	mock.lockCommitFiles.Lock()
	mock.calls.CommitFiles = append(mock.calls.CommitFiles, callInfo)
	mock.lockCommitFiles.Unlock()
	return mock.CommitFilesFunc(ctx, hash)
}

// CommitFilesCalls gets all the calls that were made to CommitFiles.
// Check the length with:
//
//	len(mockedRepo.CommitFilesCalls())
func (mock *RepoMock) CommitFilesCalls() []struct {
	Ctx  context.Context
	Hash string
} {
	var calls []struct {
		Ctx  context.Context
		Hash string
	}
	mock.lockCommitFiles.RLock()
	calls = mock.calls.CommitFiles
	mock.lockCommitFiles.RUnlock()
	return calls
}

// CommitMessages calls CommitMessagesFunc.
func (mock *RepoMock) CommitMessages(ctx context.Context, n int) ([]string, error) {
	if mock.CommitMessagesFunc == nil {
		panic("RepoMock.CommitMessagesFunc: method is nil but Repo.CommitMessages was just called")
	}
	callInfo := struct {
		Ctx context.Context
		N   int
	}{
		Ctx: ctx,
		N:   n,
	}
	mock.lockCommitMessages.Lock()
	mock.calls.CommitMessages = append(mock.calls.CommitMessages, callInfo)
	mock.lockCommitMessages.Unlock()
	return mock.CommitMessagesFunc(ctx, n)
}

// CommitMessagesCalls gets all the calls that were made to CommitMessages.
// Check the length with:
//
//	len(mockedRepo.CommitMessagesCalls())
func (mock *RepoMock) CommitMessagesCalls() []struct {
	Ctx context.Context
	N   int
} {
	var calls []struct {
		Ctx context.Context
		N   int
	}
	mock.lockCommitMessages.RLock()
	calls = mock.calls.CommitMessages
	mock.lockCommitMessages.RUnlock()
	return calls
}

// ConflictRegions calls ConflictRegionsFunc.
func (mock *RepoMock) ConflictRegions(path string) ([]conflict.Region, error) {
	if mock.ConflictRegionsFunc == nil {
		panic("RepoMock.ConflictRegionsFunc: method is nil but Repo.ConflictRegions was just called")
	}
	callInfo := struct {
		Path string
	}{
		Path: path,
	}
	mock.lockConflictRegions.Lock()
	mock.calls.ConflictRegions = append(mock.calls.ConflictRegions, callInfo)
	mock.lockConflictRegions.Unlock()
	return mock.ConflictRegionsFunc(path)
}

// ConflictRegionsCalls gets all the calls that were made to ConflictRegions.
// Check the length with:
//
//	len(mockedRepo.ConflictRegionsCalls())
func (mock *RepoMock) ConflictRegionsCalls() []struct {
	Path string
} {
	var calls []struct {
		Path string
	}
	mock.lockConflictRegions.RLock()
	calls = mock.calls.ConflictRegions
	mock.lockConflictRegions.RUnlock()
	return calls
}

// ContinueCmd calls ContinueCmdFunc.
func (mock *RepoMock) ContinueCmd(state gitops.RepoState) (*exec.Cmd, error) {
	if mock.ContinueCmdFunc == nil {
		panic("RepoMock.ContinueCmdFunc: method is nil but Repo.ContinueCmd was just called")
	}
	callInfo := struct {
		State gitops.RepoState
	}{
		State: state,
	}
	mock.lockContinueCmd.Lock()
	mock.calls.ContinueCmd = append(mock.calls.ContinueCmd, callInfo)
	mock.lockContinueCmd.Unlock()
	return mock.ContinueCmdFunc(state)
}

// ContinueCmdCalls gets all the calls that were made to ContinueCmd.
// Check the length with:
//
//	len(mockedRepo.ContinueCmdCalls())
func (mock *RepoMock) ContinueCmdCalls() []struct {
	State gitops.RepoState
} {
	var calls []struct {
		State gitops.RepoState
	}
	mock.lockContinueCmd.RLock()
	calls = mock.calls.ContinueCmd
	mock.lockContinueCmd.RUnlock()
	return calls
}

// CreateBranch calls CreateBranchFunc.
func (mock *RepoMock) CreateBranch(ctx context.Context, name string, base string, checkout bool) error {
	if mock.CreateBranchFunc == nil {
		panic("RepoMock.CreateBranchFunc: method is nil but Repo.CreateBranch was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		Name     string
		Base     string
		Checkout bool
	}{
		Ctx:      ctx,
		Name:     name,
		Base:     base,
		Checkout: checkout,
	}
	mock.lockCreateBranch.Lock()
	mock.calls.CreateBranch = append(mock.calls.CreateBranch, callInfo)
	mock.lockCreateBranch.Unlock()
	return mock.CreateBranchFunc(ctx, name, base, checkout)
}

// CreateBranchCalls gets all the calls that were made to CreateBranch.
// Check the length with:
//
//	len(mockedRepo.CreateBranchCalls())
func (mock *RepoMock) CreateBranchCalls() []struct {
	Ctx      context.Context
	Name     string
	Base     string
	Checkout bool
} {
	var calls []struct {
		Ctx      context.Context
		Name     string
		Base     string
		Checkout bool
	}
	mock.lockCreateBranch.RLock()
	calls = mock.calls.CreateBranch
	mock.lockCreateBranch.RUnlock()
	return calls
}

// DeleteBranch calls DeleteBranchFunc.
func (mock *RepoMock) DeleteBranch(ctx context.Context, name string, force bool) error {
	if mock.DeleteBranchFunc == nil {
		panic("RepoMock.DeleteBranchFunc: method is nil but Repo.DeleteBranch was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Name  string
		Force bool
	}{
		Ctx:   ctx,
		Name:  name,
		Force: force,
	}
	mock.lockDeleteBranch.Lock()
	mock.calls.DeleteBranch = append(mock.calls.DeleteBranch, callInfo)
	mock.lockDeleteBranch.Unlock()
	return mock.DeleteBranchFunc(ctx, name, force)
}

// DeleteBranchCalls gets all the calls that were made to DeleteBranch.
// Check the length with:
//
//	len(mockedRepo.DeleteBranchCalls())
func (mock *RepoMock) DeleteBranchCalls() []struct {
	Ctx   context.Context
	Name  string
	Force bool
} {
	var calls []struct {
		Ctx   context.Context
		Name  string
		Force bool
	}
	mock.lockDeleteBranch.RLock()
	calls = mock.calls.DeleteBranch
	mock.lockDeleteBranch.RUnlock()
	return calls
}

// Discard calls DiscardFunc.
func (mock *RepoMock) Discard(ctx context.Context, f gitops.StatusEntry, scope gitops.DiscardScope, unborn bool) error {
	if mock.DiscardFunc == nil {
		panic("RepoMock.DiscardFunc: method is nil but Repo.Discard was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		F      gitops.StatusEntry
		Scope  gitops.DiscardScope
		Unborn bool
	}{
		Ctx:    ctx,
		F:      f,
		Scope:  scope,
		Unborn: unborn,
	}
	mock.lockDiscard.Lock()
	mock.calls.Discard = append(mock.calls.Discard, callInfo)
	mock.lockDiscard.Unlock()
	return mock.DiscardFunc(ctx, f, scope, unborn)
}

// DiscardCalls gets all the calls that were made to Discard.
// Check the length with:
//
//	len(mockedRepo.DiscardCalls())
func (mock *RepoMock) DiscardCalls() []struct {
	Ctx    context.Context
	F      gitops.StatusEntry
	Scope  gitops.DiscardScope
	Unborn bool
} {
	var calls []struct {
		Ctx    context.Context
		F      gitops.StatusEntry
		Scope  gitops.DiscardScope
		Unborn bool
	}
	mock.lockDiscard.RLock()
	calls = mock.calls.Discard
	mock.lockDiscard.RUnlock()
	return calls
}

// FetchCmd calls FetchCmdFunc.
func (mock *RepoMock) FetchCmd(all bool, prune bool) *exec.Cmd {
	if mock.FetchCmdFunc == nil {
		panic("RepoMock.FetchCmdFunc: method is nil but Repo.FetchCmd was just called")
	}
	callInfo := struct {
		All   bool
		Prune bool
	}{
		All:   all,
		Prune: prune,
	}
	mock.lockFetchCmd.Lock()
	mock.calls.FetchCmd = append(mock.calls.FetchCmd, callInfo)
	mock.lockFetchCmd.Unlock()
	return mock.FetchCmdFunc(all, prune)
}

// FetchCmdCalls gets all the calls that were made to FetchCmd.
// Check the length with:
//
//	len(mockedRepo.FetchCmdCalls())
func (mock *RepoMock) FetchCmdCalls() []struct {
	All   bool
	Prune bool
} {
	var calls []struct {
		All   bool
		Prune bool
	}
	mock.lockFetchCmd.RLock()
	calls = mock.calls.FetchCmd
	mock.lockFetchCmd.RUnlock()
	return calls
}

// GPGSignEnabled calls GPGSignEnabledFunc.
func (mock *RepoMock) GPGSignEnabled(ctx context.Context) bool {
	if mock.GPGSignEnabledFunc == nil {
		panic("RepoMock.GPGSignEnabledFunc: method is nil but Repo.GPGSignEnabled was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGPGSignEnabled.Lock()
	mock.calls.GPGSignEnabled = append(mock.calls.GPGSignEnabled, callInfo)
	mock.lockGPGSignEnabled.Unlock()
	return mock.GPGSignEnabledFunc(ctx)
}

// GPGSignEnabledCalls gets all the calls that were made to GPGSignEnabled.
// Check the length with:
//
//	len(mockedRepo.GPGSignEnabledCalls())
func (mock *RepoMock) GPGSignEnabledCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGPGSignEnabled.RLock()
	calls = mock.calls.GPGSignEnabled
	mock.lockGPGSignEnabled.RUnlock()
	return calls
}

// HasStagedChanges calls HasStagedChangesFunc.
func (mock *RepoMock) HasStagedChanges(ctx context.Context) (bool, error) {
	if mock.HasStagedChangesFunc == nil {
		panic("RepoMock.HasStagedChangesFunc: method is nil but Repo.HasStagedChanges was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockHasStagedChanges.Lock()
	mock.calls.HasStagedChanges = append(mock.calls.HasStagedChanges, callInfo)
	mock.lockHasStagedChanges.Unlock()
	return mock.HasStagedChangesFunc(ctx)
}

// HasStagedChangesCalls gets all the calls that were made to HasStagedChanges.
// Check the length with:
//
//	len(mockedRepo.HasStagedChangesCalls())
func (mock *RepoMock) HasStagedChangesCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockHasStagedChanges.RLock()
	calls = mock.calls.HasStagedChanges
	mock.lockHasStagedChanges.RUnlock()
	return calls
}

// LastCommitMessage calls LastCommitMessageFunc.
func (mock *RepoMock) LastCommitMessage(ctx context.Context) (string, error) {
	if mock.LastCommitMessageFunc == nil {
		panic("RepoMock.LastCommitMessageFunc: method is nil but Repo.LastCommitMessage was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockLastCommitMessage.Lock()
	mock.calls.LastCommitMessage = append(mock.calls.LastCommitMessage, callInfo)
	mock.lockLastCommitMessage.Unlock()
	return mock.LastCommitMessageFunc(ctx)
}

// LastCommitMessageCalls gets all the calls that were made to LastCommitMessage.
// Check the length with:
//
//	len(mockedRepo.LastCommitMessageCalls())
func (mock *RepoMock) LastCommitMessageCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockLastCommitMessage.RLock()
	calls = mock.calls.LastCommitMessage
	mock.lockLastCommitMessage.RUnlock()
	return calls
}

// Log calls LogFunc.
func (mock *RepoMock) Log(ctx context.Context, ref string, limit int) ([]gitops.Commit, error) {
	if mock.LogFunc == nil {
		panic("RepoMock.LogFunc: method is nil but Repo.Log was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Ref   string
		Limit int
	}{
		Ctx:   ctx,
		Ref:   ref,
		Limit: limit,
	}
	mock.lockLog.Lock()
	mock.calls.Log = append(mock.calls.Log, callInfo)
	mock.lockLog.Unlock()
	return mock.LogFunc(ctx, ref, limit)
}

// LogCalls gets all the calls that were made to Log.
// Check the length with:
//
//	len(mockedRepo.LogCalls())
func (mock *RepoMock) LogCalls() []struct {
	Ctx   context.Context
	Ref   string
	Limit int
} {
	var calls []struct {
		Ctx   context.Context
		Ref   string
		Limit int
	}
	mock.lockLog.RLock()
	calls = mock.calls.Log
	mock.lockLog.RUnlock()
	return calls
}

// Merge calls MergeFunc.
func (mock *RepoMock) Merge(ctx context.Context, name string, o gitops.MergeOpts) error {
	if mock.MergeFunc == nil {
		panic("RepoMock.MergeFunc: method is nil but Repo.Merge was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Name string
		O    gitops.MergeOpts
	}{
		Ctx:  ctx,
		Name: name,
		O:    o,
	}
	mock.lockMerge.Lock()
	mock.calls.Merge = append(mock.calls.Merge, callInfo)
	mock.lockMerge.Unlock()
	return mock.MergeFunc(ctx, name, o)
}

// MergeCalls gets all the calls that were made to Merge.
// Check the length with:
//
//	len(mockedRepo.MergeCalls())
func (mock *RepoMock) MergeCalls() []struct {
	Ctx  context.Context
	Name string
	O    gitops.MergeOpts
} {
	var calls []struct {
		Ctx  context.Context
		Name string
		O    gitops.MergeOpts
	}
	mock.lockMerge.RLock()
	calls = mock.calls.Merge
	mock.lockMerge.RUnlock()
	return calls
}

// PullCmd calls PullCmdFunc.
func (mock *RepoMock) PullCmd(o gitops.PullOpts) *exec.Cmd {
	if mock.PullCmdFunc == nil {
		panic("RepoMock.PullCmdFunc: method is nil but Repo.PullCmd was just called")
	}
	callInfo := struct {
		O gitops.PullOpts
	}{
		O: o,
	}
	mock.lockPullCmd.Lock()
	mock.calls.PullCmd = append(mock.calls.PullCmd, callInfo)
	mock.lockPullCmd.Unlock()
	return mock.PullCmdFunc(o)
}

// PullCmdCalls gets all the calls that were made to PullCmd.
// Check the length with:
//
//	len(mockedRepo.PullCmdCalls())
func (mock *RepoMock) PullCmdCalls() []struct {
	O gitops.PullOpts
} {
	var calls []struct {
		O gitops.PullOpts
	}
	mock.lockPullCmd.RLock()
	calls = mock.calls.PullCmd
	mock.lockPullCmd.RUnlock()
	return calls
}

// PushCmd calls PushCmdFunc.
func (mock *RepoMock) PushCmd(o gitops.PushOpts) *exec.Cmd {
	if mock.PushCmdFunc == nil {
		panic("RepoMock.PushCmdFunc: method is nil but Repo.PushCmd was just called")
	}
	callInfo := struct {
		O gitops.PushOpts
	}{
		O: o,
	}
	mock.lockPushCmd.Lock()
	mock.calls.PushCmd = append(mock.calls.PushCmd, callInfo)
	mock.lockPushCmd.Unlock()
	return mock.PushCmdFunc(o)
}

// PushCmdCalls gets all the calls that were made to PushCmd.
// Check the length with:
//
//	len(mockedRepo.PushCmdCalls())
func (mock *RepoMock) PushCmdCalls() []struct {
	O gitops.PushOpts
} {
	var calls []struct {
		O gitops.PushOpts
	}
	mock.lockPushCmd.RLock()
	calls = mock.calls.PushCmd
	mock.lockPushCmd.RUnlock()
	return calls
}

// RangeDiff calls RangeDiffFunc.
func (mock *RepoMock) RangeDiff(ctx context.Context, ref string, contextLines int) (string, error) {
	if mock.RangeDiffFunc == nil {
		panic("RepoMock.RangeDiffFunc: method is nil but Repo.RangeDiff was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		Ref          string
		ContextLines int
	}{
		Ctx:          ctx,
		Ref:          ref,
		ContextLines: contextLines,
	}
	mock.lockRangeDiff.Lock()
	mock.calls.RangeDiff = append(mock.calls.RangeDiff, callInfo)
	mock.lockRangeDiff.Unlock()
	return mock.RangeDiffFunc(ctx, ref, contextLines)
}

// RangeDiffCalls gets all the calls that were made to RangeDiff.
// Check the length with:
//
//	len(mockedRepo.RangeDiffCalls())
func (mock *RepoMock) RangeDiffCalls() []struct {
	Ctx          context.Context
	Ref          string
	ContextLines int
} {
	var calls []struct {
		Ctx          context.Context
		Ref          string
		ContextLines int
	}
	mock.lockRangeDiff.RLock()
	calls = mock.calls.RangeDiff
	mock.lockRangeDiff.RUnlock()
	return calls
}

// Rebase calls RebaseFunc.
func (mock *RepoMock) Rebase(ctx context.Context, onto string, o gitops.RebaseOpts) error {
	if mock.RebaseFunc == nil {
		panic("RepoMock.RebaseFunc: method is nil but Repo.Rebase was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Onto string
		O    gitops.RebaseOpts
	}{
		Ctx:  ctx,
		Onto: onto,
		O:    o,
	}
	mock.lockRebase.Lock()
	mock.calls.Rebase = append(mock.calls.Rebase, callInfo)
	mock.lockRebase.Unlock()
	return mock.RebaseFunc(ctx, onto, o)
}

// RebaseCalls gets all the calls that were made to Rebase.
// Check the length with:
//
//	len(mockedRepo.RebaseCalls())
func (mock *RepoMock) RebaseCalls() []struct {
	Ctx  context.Context
	Onto string
	O    gitops.RebaseOpts
} {
	var calls []struct {
		Ctx  context.Context
		Onto string
		O    gitops.RebaseOpts
	}
	mock.lockRebase.RLock()
	calls = mock.calls.Rebase
	mock.lockRebase.RUnlock()
	return calls
}

// Remotes calls RemotesFunc.
func (mock *RepoMock) Remotes(ctx context.Context) ([]string, error) {
	if mock.RemotesFunc == nil {
		panic("RepoMock.RemotesFunc: method is nil but Repo.Remotes was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockRemotes.Lock()
	mock.calls.Remotes = append(mock.calls.Remotes, callInfo)
	mock.lockRemotes.Unlock()
	return mock.RemotesFunc(ctx)
}

// RemotesCalls gets all the calls that were made to Remotes.
// Check the length with:
//
//	len(mockedRepo.RemotesCalls())
func (mock *RepoMock) RemotesCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockRemotes.RLock()
	calls = mock.calls.Remotes
	mock.lockRemotes.RUnlock()
	return calls
}

// RenameBranch calls RenameBranchFunc.
func (mock *RepoMock) RenameBranch(ctx context.Context, oldName string, newName string) error {
	if mock.RenameBranchFunc == nil {
		panic("RepoMock.RenameBranchFunc: method is nil but Repo.RenameBranch was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		OldName string
		NewName string
	}{
		Ctx:     ctx,
		OldName: oldName,
		NewName: newName,
	}
	mock.lockRenameBranch.Lock()
	mock.calls.RenameBranch = append(mock.calls.RenameBranch, callInfo)
	mock.lockRenameBranch.Unlock()
	return mock.RenameBranchFunc(ctx, oldName, newName)
}

// RenameBranchCalls gets all the calls that were made to RenameBranch.
// Check the length with:
//
//	len(mockedRepo.RenameBranchCalls())
func (mock *RepoMock) RenameBranchCalls() []struct {
	Ctx     context.Context
	OldName string
	NewName string
} {
	var calls []struct {
		Ctx     context.Context
		OldName string
		NewName string
	}
	mock.lockRenameBranch.RLock()
	calls = mock.calls.RenameBranch
	mock.lockRenameBranch.RUnlock()
	return calls
}

// Reset calls ResetFunc.
func (mock *RepoMock) Reset(ctx context.Context, ref string, mode gitops.ResetMode) error {
	if mock.ResetFunc == nil {
		panic("RepoMock.ResetFunc: method is nil but Repo.Reset was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Ref  string
		Mode gitops.ResetMode
	}{
		Ctx:  ctx,
		Ref:  ref,
		Mode: mode,
	}
	mock.lockReset.Lock()
	mock.calls.Reset = append(mock.calls.Reset, callInfo)
	mock.lockReset.Unlock()
	return mock.ResetFunc(ctx, ref, mode)
}

// ResetCalls gets all the calls that were made to Reset.
// Check the length with:
//
//	len(mockedRepo.ResetCalls())
func (mock *RepoMock) ResetCalls() []struct {
	Ctx  context.Context
	Ref  string
	Mode gitops.ResetMode
} {
	var calls []struct {
		Ctx  context.Context
		Ref  string
		Mode gitops.ResetMode
	}
	mock.lockReset.RLock()
	calls = mock.calls.Reset
	mock.lockReset.RUnlock()
	return calls
}

// ResolveConflict calls ResolveConflictFunc.
func (mock *RepoMock) ResolveConflict(ctx context.Context, path string, ours bool) error {
	if mock.ResolveConflictFunc == nil {
		panic("RepoMock.ResolveConflictFunc: method is nil but Repo.ResolveConflict was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Path string
		Ours bool
	}{
		Ctx:  ctx,
		Path: path,
		Ours: ours,
	}
	mock.lockResolveConflict.Lock()
	mock.calls.ResolveConflict = append(mock.calls.ResolveConflict, callInfo)
	mock.lockResolveConflict.Unlock()
	return mock.ResolveConflictFunc(ctx, path, ours)
}

// ResolveConflictCalls gets all the calls that were made to ResolveConflict.
// Check the length with:
//
//	len(mockedRepo.ResolveConflictCalls())
func (mock *RepoMock) ResolveConflictCalls() []struct {
	Ctx  context.Context
	Path string
	Ours bool
} {
	var calls []struct {
		Ctx  context.Context
		Path string
		Ours bool
	}
	mock.lockResolveConflict.RLock()
	calls = mock.calls.ResolveConflict
	mock.lockResolveConflict.RUnlock()
	return calls
}

// ResolveConflictRegion calls ResolveConflictRegionFunc.
func (mock *RepoMock) ResolveConflictRegion(path string, index int, choice conflict.Choice) error {
	if mock.ResolveConflictRegionFunc == nil {
		panic("RepoMock.ResolveConflictRegionFunc: method is nil but Repo.ResolveConflictRegion was just called")
	}
	callInfo := struct {
		Path   string
		Index  int
		Choice conflict.Choice
	}{
		Path:   path,
		Index:  index,
		Choice: choice,
	}
	mock.lockResolveConflictRegion.Lock()
	mock.calls.ResolveConflictRegion = append(mock.calls.ResolveConflictRegion, callInfo)
	mock.lockResolveConflictRegion.Unlock()
	return mock.ResolveConflictRegionFunc(path, index, choice)
}

// ResolveConflictRegionCalls gets all the calls that were made to ResolveConflictRegion.
// Check the length with:
//
//	len(mockedRepo.ResolveConflictRegionCalls())
func (mock *RepoMock) ResolveConflictRegionCalls() []struct {
	Path   string
	Index  int
	Choice conflict.Choice
} {
	var calls []struct {
		Path   string
		Index  int
		Choice conflict.Choice
	}
	mock.lockResolveConflictRegion.RLock()
	calls = mock.calls.ResolveConflictRegion
	mock.lockResolveConflictRegion.RUnlock()
	return calls
}

// SetUpstream calls SetUpstreamFunc.
func (mock *RepoMock) SetUpstream(ctx context.Context, branch string, remote string, remoteBranch string) error {
	if mock.SetUpstreamFunc == nil {
		panic("RepoMock.SetUpstreamFunc: method is nil but Repo.SetUpstream was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		Branch       string
		Remote       string
		RemoteBranch string
	}{
		Ctx:          ctx,
		Branch:       branch,
		Remote:       remote,
		RemoteBranch: remoteBranch,
	}
	mock.lockSetUpstream.Lock()
	mock.calls.SetUpstream = append(mock.calls.SetUpstream, callInfo)
	mock.lockSetUpstream.Unlock()
	return mock.SetUpstreamFunc(ctx, branch, remote, remoteBranch)
}

// SetUpstreamCalls gets all the calls that were made to SetUpstream.
// Check the length with:
//
//	len(mockedRepo.SetUpstreamCalls())
func (mock *RepoMock) SetUpstreamCalls() []struct {
	Ctx          context.Context
	Branch       string
	Remote       string
	RemoteBranch string
} {
	var calls []struct {
		Ctx          context.Context
		Branch       string
		Remote       string
		RemoteBranch string
	}
	mock.lockSetUpstream.RLock()
	calls = mock.calls.SetUpstream
	mock.lockSetUpstream.RUnlock()
	return calls
}

// StageAll calls StageAllFunc.
func (mock *RepoMock) StageAll(ctx context.Context) error {
	if mock.StageAllFunc == nil {
		panic("RepoMock.StageAllFunc: method is nil but Repo.StageAll was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockStageAll.Lock()
	mock.calls.StageAll = append(mock.calls.StageAll, callInfo)
	mock.lockStageAll.Unlock()
	return mock.StageAllFunc(ctx)
}

// StageAllCalls gets all the calls that were made to StageAll.
// Check the length with:
//
//	len(mockedRepo.StageAllCalls())
func (mock *RepoMock) StageAllCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockStageAll.RLock()
	calls = mock.calls.StageAll
	mock.lockStageAll.RUnlock()
	return calls
}

// StageFiles calls StageFilesFunc.
func (mock *RepoMock) StageFiles(ctx context.Context, paths []string) error {
	if mock.StageFilesFunc == nil {
		panic("RepoMock.StageFilesFunc: method is nil but Repo.StageFiles was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Paths []string
	}{
		Ctx:   ctx,
		Paths: paths,
	}
	mock.lockStageFiles.Lock()
	mock.calls.StageFiles = append(mock.calls.StageFiles, callInfo)
	mock.lockStageFiles.Unlock()
	return mock.StageFilesFunc(ctx, paths)
}

// StageFilesCalls gets all the calls that were made to StageFiles.
// Check the length with:
//
//	len(mockedRepo.StageFilesCalls())
func (mock *RepoMock) StageFilesCalls() []struct {
	Ctx   context.Context
	Paths []string
} {
	var calls []struct {
		Ctx   context.Context
		Paths []string
	}
	mock.lockStageFiles.RLock()
	calls = mock.calls.StageFiles
	mock.lockStageFiles.RUnlock()
	return calls
}

// StagingDiff calls StagingDiffFunc.
func (mock *RepoMock) StagingDiff(ctx context.Context, spec gitops.DiffSpec) (string, error) {
	if mock.StagingDiffFunc == nil {
		panic("RepoMock.StagingDiffFunc: method is nil but Repo.StagingDiff was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Spec gitops.DiffSpec
	}{
		Ctx:  ctx,
		Spec: spec,
	}
	mock.lockStagingDiff.Lock()
	mock.calls.StagingDiff = append(mock.calls.StagingDiff, callInfo)
	mock.lockStagingDiff.Unlock()
	return mock.StagingDiffFunc(ctx, spec)
}

// StagingDiffCalls gets all the calls that were made to StagingDiff.
// Check the length with:
//
//	len(mockedRepo.StagingDiffCalls())
func (mock *RepoMock) StagingDiffCalls() []struct {
	Ctx  context.Context
	Spec gitops.DiffSpec
} {
	var calls []struct {
		Ctx  context.Context
		Spec gitops.DiffSpec
	}
	mock.lockStagingDiff.RLock()
	calls = mock.calls.StagingDiff
	mock.lockStagingDiff.RUnlock()
	return calls
}

// StashApply calls StashApplyFunc.
func (mock *RepoMock) StashApply(ctx context.Context, index int) error {
	if mock.StashApplyFunc == nil {
		panic("RepoMock.StashApplyFunc: method is nil but Repo.StashApply was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Index int
	}{
		Ctx:   ctx,
		Index: index,
	}
	mock.lockStashApply.Lock()
	mock.calls.StashApply = append(mock.calls.StashApply, callInfo)
	mock.lockStashApply.Unlock()
	return mock.StashApplyFunc(ctx, index)
}

// StashApplyCalls gets all the calls that were made to StashApply.
// Check the length with:
//
//	len(mockedRepo.StashApplyCalls())
func (mock *RepoMock) StashApplyCalls() []struct {
	Ctx   context.Context
	Index int
} {
	var calls []struct {
		Ctx   context.Context
		Index int
	}
	mock.lockStashApply.RLock()
	calls = mock.calls.StashApply
	mock.lockStashApply.RUnlock()
	return calls
}

// StashDrop calls StashDropFunc.
func (mock *RepoMock) StashDrop(ctx context.Context, index int) error {
	if mock.StashDropFunc == nil {
		panic("RepoMock.StashDropFunc: method is nil but Repo.StashDrop was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Index int
	}{
		Ctx:   ctx,
		Index: index,
	}
	mock.lockStashDrop.Lock()
	mock.calls.StashDrop = append(mock.calls.StashDrop, callInfo)
	mock.lockStashDrop.Unlock()
	return mock.StashDropFunc(ctx, index)
}

// StashDropCalls gets all the calls that were made to StashDrop.
// Check the length with:
//
//	len(mockedRepo.StashDropCalls())
func (mock *RepoMock) StashDropCalls() []struct {
	Ctx   context.Context
	Index int
} {
	var calls []struct {
		Ctx   context.Context
		Index int
	}
	mock.lockStashDrop.RLock()
	calls = mock.calls.StashDrop
	mock.lockStashDrop.RUnlock()
	return calls
}

// StashFiles calls StashFilesFunc.
func (mock *RepoMock) StashFiles(ctx context.Context, index int) ([]git.FileEntry, error) {
	if mock.StashFilesFunc == nil {
		panic("RepoMock.StashFilesFunc: method is nil but Repo.StashFiles was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Index int
	}{
		Ctx:   ctx,
		Index: index,
	}
	mock.lockStashFiles.Lock()
	mock.calls.StashFiles = append(mock.calls.StashFiles, callInfo)
	mock.lockStashFiles.Unlock()
	return mock.StashFilesFunc(ctx, index)
}

// StashFilesCalls gets all the calls that were made to StashFiles.
// Check the length with:
//
//	len(mockedRepo.StashFilesCalls())
func (mock *RepoMock) StashFilesCalls() []struct {
	Ctx   context.Context
	Index int
} {
	var calls []struct {
		Ctx   context.Context
		Index int
	}
	mock.lockStashFiles.RLock()
	calls = mock.calls.StashFiles
	mock.lockStashFiles.RUnlock()
	return calls
}

// StashPop calls StashPopFunc.
func (mock *RepoMock) StashPop(ctx context.Context, index int) error {
	if mock.StashPopFunc == nil {
		panic("RepoMock.StashPopFunc: method is nil but Repo.StashPop was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Index int
	}{
		Ctx:   ctx,
		Index: index,
	}
	mock.lockStashPop.Lock()
	mock.calls.StashPop = append(mock.calls.StashPop, callInfo)
	mock.lockStashPop.Unlock()
	return mock.StashPopFunc(ctx, index)
}

// StashPopCalls gets all the calls that were made to StashPop.
// Check the length with:
//
//	len(mockedRepo.StashPopCalls())
func (mock *RepoMock) StashPopCalls() []struct {
	Ctx   context.Context
	Index int
} {
	var calls []struct {
		Ctx   context.Context
		Index int
	}
	mock.lockStashPop.RLock()
	calls = mock.calls.StashPop
	mock.lockStashPop.RUnlock()
	return calls
}

// StashPush calls StashPushFunc.
func (mock *RepoMock) StashPush(ctx context.Context, o gitops.StashPushOpts) error {
	if mock.StashPushFunc == nil {
		panic("RepoMock.StashPushFunc: method is nil but Repo.StashPush was just called")
	}
	callInfo := struct {
		Ctx context.Context
		O   gitops.StashPushOpts
	}{
		Ctx: ctx,
		O:   o,
	}
	mock.lockStashPush.Lock()
	mock.calls.StashPush = append(mock.calls.StashPush, callInfo)
	mock.lockStashPush.Unlock()
	return mock.StashPushFunc(ctx, o)
}

// StashPushCalls gets all the calls that were made to StashPush.
// Check the length with:
//
//	len(mockedRepo.StashPushCalls())
func (mock *RepoMock) StashPushCalls() []struct {
	Ctx context.Context
	O   gitops.StashPushOpts
} {
	var calls []struct {
		Ctx context.Context
		O   gitops.StashPushOpts
	}
	mock.lockStashPush.RLock()
	calls = mock.calls.StashPush
	mock.lockStashPush.RUnlock()
	return calls
}

// StashStagedSupported calls StashStagedSupportedFunc.
func (mock *RepoMock) StashStagedSupported(ctx context.Context) bool {
	if mock.StashStagedSupportedFunc == nil {
		panic("RepoMock.StashStagedSupportedFunc: method is nil but Repo.StashStagedSupported was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockStashStagedSupported.Lock()
	mock.calls.StashStagedSupported = append(mock.calls.StashStagedSupported, callInfo)
	mock.lockStashStagedSupported.Unlock()
	return mock.StashStagedSupportedFunc(ctx)
}

// StashStagedSupportedCalls gets all the calls that were made to StashStagedSupported.
// Check the length with:
//
//	len(mockedRepo.StashStagedSupportedCalls())
func (mock *RepoMock) StashStagedSupportedCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockStashStagedSupported.RLock()
	calls = mock.calls.StashStagedSupported
	mock.lockStashStagedSupported.RUnlock()
	return calls
}

// Stashes calls StashesFunc.
func (mock *RepoMock) Stashes(ctx context.Context) ([]gitops.StashEntry, error) {
	if mock.StashesFunc == nil {
		panic("RepoMock.StashesFunc: method is nil but Repo.Stashes was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockStashes.Lock()
	mock.calls.Stashes = append(mock.calls.Stashes, callInfo)
	mock.lockStashes.Unlock()
	return mock.StashesFunc(ctx)
}

// StashesCalls gets all the calls that were made to Stashes.
// Check the length with:
//
//	len(mockedRepo.StashesCalls())
func (mock *RepoMock) StashesCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockStashes.RLock()
	calls = mock.calls.Stashes
	mock.lockStashes.RUnlock()
	return calls
}

// Status calls StatusFunc.
func (mock *RepoMock) Status(ctx context.Context) (gitops.Status, error) {
	if mock.StatusFunc == nil {
		panic("RepoMock.StatusFunc: method is nil but Repo.Status was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockStatus.Lock()
	mock.calls.Status = append(mock.calls.Status, callInfo)
	mock.lockStatus.Unlock()
	return mock.StatusFunc(ctx)
}

// StatusCalls gets all the calls that were made to Status.
// Check the length with:
//
//	len(mockedRepo.StatusCalls())
func (mock *RepoMock) StatusCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockStatus.RLock()
	calls = mock.calls.Status
	mock.lockStatus.RUnlock()
	return calls
}

// UnstageAll calls UnstageAllFunc.
func (mock *RepoMock) UnstageAll(ctx context.Context, unborn bool) error {
	if mock.UnstageAllFunc == nil {
		panic("RepoMock.UnstageAllFunc: method is nil but Repo.UnstageAll was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Unborn bool
	}{
		Ctx:    ctx,
		Unborn: unborn,
	}
	mock.lockUnstageAll.Lock()
	mock.calls.UnstageAll = append(mock.calls.UnstageAll, callInfo)
	mock.lockUnstageAll.Unlock()
	return mock.UnstageAllFunc(ctx, unborn)
}

// UnstageAllCalls gets all the calls that were made to UnstageAll.
// Check the length with:
//
//	len(mockedRepo.UnstageAllCalls())
func (mock *RepoMock) UnstageAllCalls() []struct {
	Ctx    context.Context
	Unborn bool
} {
	var calls []struct {
		Ctx    context.Context
		Unborn bool
	}
	mock.lockUnstageAll.RLock()
	calls = mock.calls.UnstageAll
	mock.lockUnstageAll.RUnlock()
	return calls
}

// UnstageDuringMerge calls UnstageDuringMergeFunc.
func (mock *RepoMock) UnstageDuringMerge(ctx context.Context, path string, unborn bool) error {
	if mock.UnstageDuringMergeFunc == nil {
		panic("RepoMock.UnstageDuringMergeFunc: method is nil but Repo.UnstageDuringMerge was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Path   string
		Unborn bool
	}{
		Ctx:    ctx,
		Path:   path,
		Unborn: unborn,
	}
	mock.lockUnstageDuringMerge.Lock()
	mock.calls.UnstageDuringMerge = append(mock.calls.UnstageDuringMerge, callInfo)
	mock.lockUnstageDuringMerge.Unlock()
	return mock.UnstageDuringMergeFunc(ctx, path, unborn)
}

// UnstageDuringMergeCalls gets all the calls that were made to UnstageDuringMerge.
// Check the length with:
//
//	len(mockedRepo.UnstageDuringMergeCalls())
func (mock *RepoMock) UnstageDuringMergeCalls() []struct {
	Ctx    context.Context
	Path   string
	Unborn bool
} {
	var calls []struct {
		Ctx    context.Context
		Path   string
		Unborn bool
	}
	mock.lockUnstageDuringMerge.RLock()
	calls = mock.calls.UnstageDuringMerge
	mock.lockUnstageDuringMerge.RUnlock()
	return calls
}

// UnstageFiles calls UnstageFilesFunc.
func (mock *RepoMock) UnstageFiles(ctx context.Context, paths []string, unborn bool) error {
	if mock.UnstageFilesFunc == nil {
		panic("RepoMock.UnstageFilesFunc: method is nil but Repo.UnstageFiles was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Paths  []string
		Unborn bool
	}{
		Ctx:    ctx,
		Paths:  paths,
		Unborn: unborn,
	}
	mock.lockUnstageFiles.Lock()
	mock.calls.UnstageFiles = append(mock.calls.UnstageFiles, callInfo)
	mock.lockUnstageFiles.Unlock()
	return mock.UnstageFilesFunc(ctx, paths, unborn)
}

// UnstageFilesCalls gets all the calls that were made to UnstageFiles.
// Check the length with:
//
//	len(mockedRepo.UnstageFilesCalls())
func (mock *RepoMock) UnstageFilesCalls() []struct {
	Ctx    context.Context
	Paths  []string
	Unborn bool
} {
	var calls []struct {
		Ctx    context.Context
		Paths  []string
		Unborn bool
	}
	mock.lockUnstageFiles.RLock()
	calls = mock.calls.UnstageFiles
	mock.lockUnstageFiles.RUnlock()
	return calls
}
