// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"sync"

	"github.com/yousysadmin/igit/internal/git"
)

// styleRendererMock is a mock implementation of tui.styleRenderer.
//
//	func TestSomethingThatUsesstyleRenderer(t *testing.T) {
//
//		// make and configure a mocked tui.styleRenderer
//		mockedstyleRenderer := &styleRendererMock{
//			AnnotationInlineFunc: func(text string) string {
//				panic("mock out the AnnotationInline method")
//			},
//			DiffCursorFunc: func(noColors bool) string {
//				panic("mock out the DiffCursor method")
//			},
//			FileAnnotationMarkFunc: func() string {
//				panic("mock out the FileAnnotationMark method")
//			},
//			FileReviewedMarkFunc: func() string {
//				panic("mock out the FileReviewedMark method")
//			},
//			FileStageMarkFunc: func() string {
//				panic("mock out the FileStageMark method")
//			},
//			FileStatusMarkFunc: func(status git.ChangeStatus) string {
//				panic("mock out the FileStatusMark method")
//			},
//			SelectionMarkFunc: func(noColors bool) string {
//				panic("mock out the SelectionMark method")
//			},
//			StageMarkFunc: func(noColors bool) string {
//				panic("mock out the StageMark method")
//			},
//			StatusBarSeparatorFunc: func() string {
//				panic("mock out the StatusBarSeparator method")
//			},
//		}
//
//		// use mockedstyleRenderer in code that requires tui.styleRenderer
//		// and then make assertions.
//
//	}
type styleRendererMock struct {
	// AnnotationInlineFunc mocks the AnnotationInline method.
	AnnotationInlineFunc func(text string) string

	// DiffCursorFunc mocks the DiffCursor method.
	DiffCursorFunc func(noColors bool) string

	// FileAnnotationMarkFunc mocks the FileAnnotationMark method.
	FileAnnotationMarkFunc func() string

	// FileReviewedMarkFunc mocks the FileReviewedMark method.
	FileReviewedMarkFunc func() string

	// FileStageMarkFunc mocks the FileStageMark method.
	FileStageMarkFunc func() string

	// FileStatusMarkFunc mocks the FileStatusMark method.
	FileStatusMarkFunc func(status git.ChangeStatus) string

	// SelectionMarkFunc mocks the SelectionMark method.
	SelectionMarkFunc func(noColors bool) string

	// StageMarkFunc mocks the StageMark method.
	StageMarkFunc func(noColors bool) string

	// StatusBarSeparatorFunc mocks the StatusBarSeparator method.
	StatusBarSeparatorFunc func() string

	// calls tracks calls to the methods.
	calls struct {
		// AnnotationInline holds details about calls to the AnnotationInline method.
		AnnotationInline []struct {
			// Text is the text argument value.
			Text string
		}
		// DiffCursor holds details about calls to the DiffCursor method.
		DiffCursor []struct {
			// NoColors is the noColors argument value.
			NoColors bool
		}
		// FileAnnotationMark holds details about calls to the FileAnnotationMark method.
		FileAnnotationMark []struct {
		}
		// FileReviewedMark holds details about calls to the FileReviewedMark method.
		FileReviewedMark []struct {
		}
		// FileStageMark holds details about calls to the FileStageMark method.
		FileStageMark []struct {
		}
		// FileStatusMark holds details about calls to the FileStatusMark method.
		FileStatusMark []struct {
			// Status is the status argument value.
			Status git.ChangeStatus
		}
		// SelectionMark holds details about calls to the SelectionMark method.
		SelectionMark []struct {
			// NoColors is the noColors argument value.
			NoColors bool
		}
		// StageMark holds details about calls to the StageMark method.
		StageMark []struct {
			// NoColors is the noColors argument value.
			NoColors bool
		}
		// StatusBarSeparator holds details about calls to the StatusBarSeparator method.
		StatusBarSeparator []struct {
		}
	}
	lockAnnotationInline   sync.RWMutex
	lockDiffCursor         sync.RWMutex
	lockFileAnnotationMark sync.RWMutex
	lockFileReviewedMark   sync.RWMutex
	lockFileStageMark      sync.RWMutex
	lockFileStatusMark     sync.RWMutex
	lockSelectionMark      sync.RWMutex
	lockStageMark          sync.RWMutex
	lockStatusBarSeparator sync.RWMutex
}

// AnnotationInline calls AnnotationInlineFunc.
func (mock *styleRendererMock) AnnotationInline(text string) string {
	if mock.AnnotationInlineFunc == nil {
		panic("styleRendererMock.AnnotationInlineFunc: method is nil but styleRenderer.AnnotationInline was just called")
	}
	callInfo := struct {
		Text string
	}{
		Text: text,
	}
	mock.lockAnnotationInline.Lock()
	mock.calls.AnnotationInline = append(mock.calls.AnnotationInline, callInfo)
	mock.lockAnnotationInline.Unlock()
	return mock.AnnotationInlineFunc(text)
}

// AnnotationInlineCalls gets all the calls that were made to AnnotationInline.
// Check the length with:
//
//	len(mockedstyleRenderer.AnnotationInlineCalls())
func (mock *styleRendererMock) AnnotationInlineCalls() []struct {
	Text string
} {
	var calls []struct {
		Text string
	}
	mock.lockAnnotationInline.RLock()
	calls = mock.calls.AnnotationInline
	mock.lockAnnotationInline.RUnlock()
	return calls
}

// DiffCursor calls DiffCursorFunc.
func (mock *styleRendererMock) DiffCursor(noColors bool) string {
	if mock.DiffCursorFunc == nil {
		panic("styleRendererMock.DiffCursorFunc: method is nil but styleRenderer.DiffCursor was just called")
	}
	callInfo := struct {
		NoColors bool
	}{
		NoColors: noColors,
	}
	mock.lockDiffCursor.Lock()
	mock.calls.DiffCursor = append(mock.calls.DiffCursor, callInfo)
	mock.lockDiffCursor.Unlock()
	return mock.DiffCursorFunc(noColors)
}

// DiffCursorCalls gets all the calls that were made to DiffCursor.
// Check the length with:
//
//	len(mockedstyleRenderer.DiffCursorCalls())
func (mock *styleRendererMock) DiffCursorCalls() []struct {
	NoColors bool
} {
	var calls []struct {
		NoColors bool
	}
	mock.lockDiffCursor.RLock()
	calls = mock.calls.DiffCursor
	mock.lockDiffCursor.RUnlock()
	return calls
}

// FileAnnotationMark calls FileAnnotationMarkFunc.
func (mock *styleRendererMock) FileAnnotationMark() string {
	if mock.FileAnnotationMarkFunc == nil {
		panic("styleRendererMock.FileAnnotationMarkFunc: method is nil but styleRenderer.FileAnnotationMark was just called")
	}
	callInfo := struct {
	}{}
	mock.lockFileAnnotationMark.Lock()
	mock.calls.FileAnnotationMark = append(mock.calls.FileAnnotationMark, callInfo)
	mock.lockFileAnnotationMark.Unlock()
	return mock.FileAnnotationMarkFunc()
}

// FileAnnotationMarkCalls gets all the calls that were made to FileAnnotationMark.
// Check the length with:
//
//	len(mockedstyleRenderer.FileAnnotationMarkCalls())
func (mock *styleRendererMock) FileAnnotationMarkCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockFileAnnotationMark.RLock()
	calls = mock.calls.FileAnnotationMark
	mock.lockFileAnnotationMark.RUnlock()
	return calls
}

// FileReviewedMark calls FileReviewedMarkFunc.
func (mock *styleRendererMock) FileReviewedMark() string {
	if mock.FileReviewedMarkFunc == nil {
		panic("styleRendererMock.FileReviewedMarkFunc: method is nil but styleRenderer.FileReviewedMark was just called")
	}
	callInfo := struct {
	}{}
	mock.lockFileReviewedMark.Lock()
	mock.calls.FileReviewedMark = append(mock.calls.FileReviewedMark, callInfo)
	mock.lockFileReviewedMark.Unlock()
	return mock.FileReviewedMarkFunc()
}

// FileReviewedMarkCalls gets all the calls that were made to FileReviewedMark.
// Check the length with:
//
//	len(mockedstyleRenderer.FileReviewedMarkCalls())
func (mock *styleRendererMock) FileReviewedMarkCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockFileReviewedMark.RLock()
	calls = mock.calls.FileReviewedMark
	mock.lockFileReviewedMark.RUnlock()
	return calls
}

// FileStageMark calls FileStageMarkFunc.
func (mock *styleRendererMock) FileStageMark() string {
	if mock.FileStageMarkFunc == nil {
		panic("styleRendererMock.FileStageMarkFunc: method is nil but styleRenderer.FileStageMark was just called")
	}
	callInfo := struct {
	}{}
	mock.lockFileStageMark.Lock()
	mock.calls.FileStageMark = append(mock.calls.FileStageMark, callInfo)
	mock.lockFileStageMark.Unlock()
	return mock.FileStageMarkFunc()
}

// FileStageMarkCalls gets all the calls that were made to FileStageMark.
// Check the length with:
//
//	len(mockedstyleRenderer.FileStageMarkCalls())
func (mock *styleRendererMock) FileStageMarkCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockFileStageMark.RLock()
	calls = mock.calls.FileStageMark
	mock.lockFileStageMark.RUnlock()
	return calls
}

// FileStatusMark calls FileStatusMarkFunc.
func (mock *styleRendererMock) FileStatusMark(status git.ChangeStatus) string {
	if mock.FileStatusMarkFunc == nil {
		panic("styleRendererMock.FileStatusMarkFunc: method is nil but styleRenderer.FileStatusMark was just called")
	}
	callInfo := struct {
		Status git.ChangeStatus
	}{
		Status: status,
	}
	mock.lockFileStatusMark.Lock()
	mock.calls.FileStatusMark = append(mock.calls.FileStatusMark, callInfo)
	mock.lockFileStatusMark.Unlock()
	return mock.FileStatusMarkFunc(status)
}

// FileStatusMarkCalls gets all the calls that were made to FileStatusMark.
// Check the length with:
//
//	len(mockedstyleRenderer.FileStatusMarkCalls())
func (mock *styleRendererMock) FileStatusMarkCalls() []struct {
	Status git.ChangeStatus
} {
	var calls []struct {
		Status git.ChangeStatus
	}
	mock.lockFileStatusMark.RLock()
	calls = mock.calls.FileStatusMark
	mock.lockFileStatusMark.RUnlock()
	return calls
}

// SelectionMark calls SelectionMarkFunc.
func (mock *styleRendererMock) SelectionMark(noColors bool) string {
	if mock.SelectionMarkFunc == nil {
		panic("styleRendererMock.SelectionMarkFunc: method is nil but styleRenderer.SelectionMark was just called")
	}
	callInfo := struct {
		NoColors bool
	}{
		NoColors: noColors,
	}
	mock.lockSelectionMark.Lock()
	mock.calls.SelectionMark = append(mock.calls.SelectionMark, callInfo)
	mock.lockSelectionMark.Unlock()
	return mock.SelectionMarkFunc(noColors)
}

// SelectionMarkCalls gets all the calls that were made to SelectionMark.
// Check the length with:
//
//	len(mockedstyleRenderer.SelectionMarkCalls())
func (mock *styleRendererMock) SelectionMarkCalls() []struct {
	NoColors bool
} {
	var calls []struct {
		NoColors bool
	}
	mock.lockSelectionMark.RLock()
	calls = mock.calls.SelectionMark
	mock.lockSelectionMark.RUnlock()
	return calls
}

// StageMark calls StageMarkFunc.
func (mock *styleRendererMock) StageMark(noColors bool) string {
	if mock.StageMarkFunc == nil {
		panic("styleRendererMock.StageMarkFunc: method is nil but styleRenderer.StageMark was just called")
	}
	callInfo := struct {
		NoColors bool
	}{
		NoColors: noColors,
	}
	mock.lockStageMark.Lock()
	mock.calls.StageMark = append(mock.calls.StageMark, callInfo)
	mock.lockStageMark.Unlock()
	return mock.StageMarkFunc(noColors)
}

// StageMarkCalls gets all the calls that were made to StageMark.
// Check the length with:
//
//	len(mockedstyleRenderer.StageMarkCalls())
func (mock *styleRendererMock) StageMarkCalls() []struct {
	NoColors bool
} {
	var calls []struct {
		NoColors bool
	}
	mock.lockStageMark.RLock()
	calls = mock.calls.StageMark
	mock.lockStageMark.RUnlock()
	return calls
}

// StatusBarSeparator calls StatusBarSeparatorFunc.
func (mock *styleRendererMock) StatusBarSeparator() string {
	if mock.StatusBarSeparatorFunc == nil {
		panic("styleRendererMock.StatusBarSeparatorFunc: method is nil but styleRenderer.StatusBarSeparator was just called")
	}
	callInfo := struct {
	}{}
	mock.lockStatusBarSeparator.Lock()
	mock.calls.StatusBarSeparator = append(mock.calls.StatusBarSeparator, callInfo)
	mock.lockStatusBarSeparator.Unlock()
	return mock.StatusBarSeparatorFunc()
}

// StatusBarSeparatorCalls gets all the calls that were made to StatusBarSeparator.
// Check the length with:
//
//	len(mockedstyleRenderer.StatusBarSeparatorCalls())
func (mock *styleRendererMock) StatusBarSeparatorCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockStatusBarSeparator.RLock()
	calls = mock.calls.StatusBarSeparator
	mock.lockStatusBarSeparator.RUnlock()
	return calls
}
